In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import numpy as np
from pykrx import stock
kospi = yf.download('^KS11')

[*********************100%%**********************]  1 of 1 completed

In [2]:
from pykrx import stock
df = stock.get_index_ohlcv_by_date("1999-12-28","2024-01-05","1001","d")
df = df.sort_index()

In [4]:
df_kospi = df[['종가']].rename(columns={'종가':'Close_KOSPI'})
df_kospi

코스피         Close_KOSPI
날짜
1999-12-28      1028.07
2000-01-04      1059.04
2000-01-05       986.31
2000-01-06       960.79
2000-01-07       948.65
...                 ...
2023-12-28      2655.28
2024-01-02      2669.81
2024-01-03      2607.31
2024-01-04      2587.02
2024-01-05      2578.08

[5928 rows x 1 columns]

## 2015 산타랠리
### 주가 상승 국면
    - 상승    127
    - 하락    121

In [24]:
santa2015 = df_kospi.loc["2015-01-02":"2015-12-30"]
santa2015

코스피         Close_KOSPI
날짜
2015-01-02      1926.44
2015-01-05      1915.75
2015-01-06      1882.45
2015-01-07      1883.83
2015-01-08      1904.65
...                 ...
2015-12-23      1999.22
2015-12-24      1990.65
2015-12-28      1964.06
2015-12-29      1966.31
2015-12-30      1961.31

[248 rows x 1 columns]

In [25]:
#다음날 종가 계산식
santa2015['Price_lag'] = santa2015['Close_KOSPI'].shift(-1)

C:\Users\LG\AppData\Local\Temp\ipykernel_12696\4032964318.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2015['Price_lag'] = santa2015['Close_KOSPI'].shift(-1)

In [26]:
#주식 홀딩하는 경우 다음 날의 기대 수익
santa2015['expected_rtns'] = santa2015['Price_lag']-santa2015['Close_KOSPI']
santa2015

C:\Users\LG\AppData\Local\Temp\ipykernel_12696\1694936080.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2015['expected_rtns'] = santa2015['Price_lag']-santa2015['Close_KOSPI']

코스피         Close_KOSPI  Price_lag  expected_rtns
날짜
2015-01-02      1926.44    1915.75         -10.69
2015-01-05      1915.75    1882.45         -33.30
2015-01-06      1882.45    1883.83           1.38
2015-01-07      1883.83    1904.65          20.82
2015-01-08      1904.65    1924.70          20.05
...                 ...        ...            ...
2015-12-23      1999.22    1990.65          -8.57
2015-12-24      1990.65    1964.06         -26.59
2015-12-28      1964.06    1966.31           2.25
2015-12-29      1966.31    1961.31          -5.00
2015-12-30      1961.31        NaN            NaN

[248 rows x 3 columns]

In [27]:
#주가 변동율 계산식: 주식 holding 시 다음날 기대수익률
santa2015['Daily_rtn_rate'] = santa2015['expected_rtns']/santa2015['Close_KOSPI']
santa2015

C:\Users\LG\AppData\Local\Temp\ipykernel_12696\3633760352.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2015['Daily_rtn_rate'] = santa2015['expected_rtns']/santa2015['Close_KOSPI']

코스피         Close_KOSPI  Price_lag  expected_rtns  Daily_rtn_rate
날짜
2015-01-02      1926.44    1915.75         -10.69       -0.005549
2015-01-05      1915.75    1882.45         -33.30       -0.017382
2015-01-06      1882.45    1883.83           1.38        0.000733
2015-01-07      1883.83    1904.65          20.82        0.011052
2015-01-08      1904.65    1924.70          20.05        0.010527
...                 ...        ...            ...             ...
2015-12-23      1999.22    1990.65          -8.57       -0.004287
2015-12-24      1990.65    1964.06         -26.59       -0.013357
2015-12-28      1964.06    1966.31           2.25        0.001146
2015-12-29      1966.31    1961.31          -5.00       -0.002543
2015-12-30      1961.31        NaN            NaN             NaN

[248 rows x 4 columns]

In [28]:
santa2015['UPDOWN'] = [1 if santa2015['Daily_rtn_rate'].loc[date] > 0 else 0 for date in santa2015.index]
santa2015

C:\Users\LG\AppData\Local\Temp\ipykernel_12696\3646208702.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2015['UPDOWN'] = [1 if santa2015['Daily_rtn_rate'].loc[date] > 0 else 0 for date in santa2015.index]

코스피         Close_KOSPI  Price_lag  expected_rtns  Daily_rtn_rate  UPDOWN
날짜
2015-01-02      1926.44    1915.75         -10.69       -0.005549       0
2015-01-05      1915.75    1882.45         -33.30       -0.017382       0
2015-01-06      1882.45    1883.83           1.38        0.000733       1
2015-01-07      1883.83    1904.65          20.82        0.011052       1
2015-01-08      1904.65    1924.70          20.05        0.010527       1
...                 ...        ...            ...             ...     ...
2015-12-23      1999.22    1990.65          -8.57       -0.004287       0
2015-12-24      1990.65    1964.06         -26.59       -0.013357       0
2015-12-28      1964.06    1966.31           2.25        0.001146       1
2015-12-29      1966.31    1961.31          -5.00       -0.002543       0
2015-12-30      1961.31        NaN            NaN             NaN       0

[248 rows x 5 columns]

In [29]:
santa2015['Phase'] = ['상승' if x == 1 else '하락' for x in santa2015['UPDOWN']]
santa2015

C:\Users\LG\AppData\Local\Temp\ipykernel_12696\1449317816.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2015['Phase'] = ['상승' if x == 1 else '하락' for x in santa2015['UPDOWN']]

코스피,Close_KOSPI,Price_lag,expected_rtns,Daily_rtn_rate,UPDOWN,Phase
날짜,,,,,,
2015-01-02,1926.44,1915.75,-10.69,-0.005549,0,하락
2015-01-05,1915.75,1882.45,-33.30,-0.017382,0,하락
2015-01-06,1882.45,1883.83,1.38,0.000733,1,상승
2015-01-07,1883.83,1904.65,20.82,0.011052,1,상승
2015-01-08,1904.65,1924.70,20.05,0.010527,1,상승
...,...,...,...,...,...,...
2015-12-23,1999.22,1990.65,-8.57,-0.004287,0,하락
2015-12-24,1990.65,1964.06,-26.59,-0.013357,0,하락
2015-12-28,1964.06,1966.31,2.25,0.001146,1,상승
2015-12-29,1966.31,1961.31,-5.00,-0.002543,0,하락
2015-12-30,1961.31,NaN,NaN,NaN,0,하락

In [30]:
santa2015['Phase'].value_counts()

Phase
상승    127
하락    121
Name: count, dtype: int64

## 2016 산타랠리
#### 주식수익률 상승 국면

In [18]:
df_kospi = df[['종가']].rename(columns={'종가':'Close_KOSPI'})
df_kospi

코스피         Close_KOSPI
날짜
1999-12-28      1028.07
2000-01-04      1059.04
2000-01-05       986.31
2000-01-06       960.79
2000-01-07       948.65
...                 ...
2023-12-28      2655.28
2024-01-02      2669.81
2024-01-03      2607.31
2024-01-04      2587.02
2024-01-05      2578.08

[5928 rows x 1 columns]

In [31]:
df_kospi.loc["2016-01-04":"2016-12-29"]

코스피         Close_KOSPI
날짜
2016-01-04      1918.76
2016-01-05      1930.53
2016-01-06      1925.43
2016-01-07      1904.33
2016-01-08      1917.62
...                 ...
2016-12-23      2035.90
2016-12-26      2037.75
2016-12-27      2042.17
2016-12-28      2024.49
2016-12-29      2026.46

[246 rows x 1 columns]

In [32]:
santa2016 = df_kospi.loc["2016-01-04":"2016-12-29"]
santa2016

코스피         Close_KOSPI
날짜
2016-01-04      1918.76
2016-01-05      1930.53
2016-01-06      1925.43
2016-01-07      1904.33
2016-01-08      1917.62
...                 ...
2016-12-23      2035.90
2016-12-26      2037.75
2016-12-27      2042.17
2016-12-28      2024.49
2016-12-29      2026.46

[246 rows x 1 columns]

In [33]:
#다음날 종가 계산식
santa2016['Price_lag'] = santa2016['Close_KOSPI'].shift(-1)

C:\Users\LG\AppData\Local\Temp\ipykernel_12696\1197240193.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2016['Price_lag'] = santa2016['Close_KOSPI'].shift(-1)

In [34]:
#주식 홀딩하는 경우 다음 날의 기대 수익
santa2016['expected_rtns'] = santa2016['Price_lag']-santa2016['Close_KOSPI']
santa2016

C:\Users\LG\AppData\Local\Temp\ipykernel_12696\3274381295.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2016['expected_rtns'] = santa2016['Price_lag']-santa2016['Close_KOSPI']

코스피         Close_KOSPI  Price_lag  expected_rtns
날짜
2016-01-04      1918.76    1930.53          11.77
2016-01-05      1930.53    1925.43          -5.10
2016-01-06      1925.43    1904.33         -21.10
2016-01-07      1904.33    1917.62          13.29
2016-01-08      1917.62    1894.84         -22.78
...                 ...        ...            ...
2016-12-23      2035.90    2037.75           1.85
2016-12-26      2037.75    2042.17           4.42
2016-12-27      2042.17    2024.49         -17.68
2016-12-28      2024.49    2026.46           1.97
2016-12-29      2026.46        NaN            NaN

[246 rows x 3 columns]

In [35]:
#주가 변동율 계산식: 주식 holding 시 다음날 기대수익률
santa2016['Daily_rtn_rate'] = santa2016['expected_rtns']/santa2016['Close_KOSPI']

santa2016['UPDOWN'] = [1 if santa2016['Daily_rtn_rate'].loc[date] > 0 else 0 for date in santa2016.index]

santa2016['Phase'] = ['상승' if x == 1 else '하락' for x in santa2016['UPDOWN']]
santa2016

C:\Users\LG\AppData\Local\Temp\ipykernel_12696\3514884594.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2016['Daily_rtn_rate'] = santa2016['expected_rtns']/santa2016['Close_KOSPI']
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\3514884594.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2016['UPDOWN'] = [1 if santa2016['Daily_rtn_rate'].loc[date] > 0 else 0 for date in santa2016.index]
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\3514884594.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2016['Phase'] = ['상승' if x == 1 else '하락' for x in santa2016['UPDOWN']]

코스피,Close_KOSPI,Price_lag,expected_rtns,Daily_rtn_rate,UPDOWN,Phase
날짜,,,,,,
2016-01-04,1918.76,1930.53,11.77,0.006134,1,상승
2016-01-05,1930.53,1925.43,-5.10,-0.002642,0,하락
2016-01-06,1925.43,1904.33,-21.10,-0.010959,0,하락
2016-01-07,1904.33,1917.62,13.29,0.006979,1,상승
2016-01-08,1917.62,1894.84,-22.78,-0.011879,0,하락
...,...,...,...,...,...,...
2016-12-23,2035.90,2037.75,1.85,0.000909,1,상승
2016-12-26,2037.75,2042.17,4.42,0.002169,1,상승
2016-12-27,2042.17,2024.49,-17.68,-0.008657,0,하락
2016-12-28,2024.49,2026.46,1.97,0.000973,1,상승
2016-12-29,2026.46,NaN,NaN,NaN,0,하락

In [36]:
santa2016['Phase'].value_counts()

Phase
상승    131
하락    115
Name: count, dtype: int64

## 2017 산타랠리
### 상승 국면
- Phase
    - 상승    133
    - 하락    110

In [42]:
santa2017 = df_kospi.loc["2017-01-02":"2017-12-28"]
santa2017

코스피         Close_KOSPI
날짜
2017-01-02      2026.16
2017-01-03      2043.97
2017-01-04      2045.64
2017-01-05      2041.95
2017-01-06      2049.12
...                 ...
2017-12-21      2429.83
2017-12-22      2440.54
2017-12-26      2427.34
2017-12-27      2436.67
2017-12-28      2467.49

[243 rows x 1 columns]

In [43]:
#다음날 종가 계산식
santa2017['Price_lag'] = santa2017['Close_KOSPI'].shift(-1)

#주식 홀딩하는 경우 다음 날의 기대 수익
santa2017['expected_rtns'] = santa2017['Price_lag']-santa2017['Close_KOSPI']

#주가 변동율 계산식: 주식 holding 시 다음날 기대수익률
santa2017['Daily_rtn_rate'] = santa2017['expected_rtns']/santa2017['Close_KOSPI']

santa2017['UPDOWN'] = [1 if santa2017['Daily_rtn_rate'].loc[date] > 0 else 0 for date in santa2017.index]

santa2017['Phase'] = ['상승' if x == 1 else '하락' for x in santa2017['UPDOWN']]
santa2017

C:\Users\LG\AppData\Local\Temp\ipykernel_12696\2594939799.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2017['Price_lag'] = santa2017['Close_KOSPI'].shift(-1)
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\2594939799.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2017['expected_rtns'] = santa2017['Price_lag']-santa2017['Close_KOSPI']
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\2594939799.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2017['Daily_rtn_rate'] = santa2017['expected_rtns']/santa2017['Close_KOSPI']
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\2594939799.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2017['UPDOWN'] = [1 if santa2017['Daily_rtn_rate'].loc[date] > 0 else 0 for date in santa2017.index]
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\2594939799.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2017['Phase'] = ['상승' if x == 1 else '하락' for x in santa2017['UPDOWN']]

코스피,Close_KOSPI,Price_lag,expected_rtns,Daily_rtn_rate,UPDOWN,Phase
날짜,,,,,,
2017-01-02,2026.16,2043.97,17.81,0.008790,1,상승
2017-01-03,2043.97,2045.64,1.67,0.000817,1,상승
2017-01-04,2045.64,2041.95,-3.69,-0.001804,0,하락
2017-01-05,2041.95,2049.12,7.17,0.003511,1,상승
2017-01-06,2049.12,2048.78,-0.34,-0.000166,0,하락
...,...,...,...,...,...,...
2017-12-21,2429.83,2440.54,10.71,0.004408,1,상승
2017-12-22,2440.54,2427.34,-13.20,-0.005409,0,하락
2017-12-26,2427.34,2436.67,9.33,0.003844,1,상승
2017-12-27,2436.67,2467.49,30.82,0.012648,1,상승
2017-12-28,2467.49,NaN,NaN,NaN,0,하락

In [45]:
santa2017['Phase'].value_counts()

Phase
상승    133
하락    110
Name: count, dtype: int64

## 산타 2018 
- 상승, 하강 동일 개수

In [49]:
santa2018 = df_kospi.loc["2018-01-02":"2018-12-28"]
santa2018

코스피         Close_KOSPI
날짜
2018-01-02      2479.65
2018-01-03      2486.35
2018-01-04      2466.46
2018-01-05      2497.52
2018-01-08      2513.28
...                 ...
2018-12-21      2061.49
2018-12-24      2055.01
2018-12-26      2028.01
2018-12-27      2028.44
2018-12-28      2041.04

[244 rows x 1 columns]

In [50]:
#다음날 종가 계산식
santa2018['Price_lag'] = santa2018['Close_KOSPI'].shift(-1)

#주식 홀딩하는 경우 다음 날의 기대 수익
santa2018['expected_rtns'] = santa2018['Price_lag']-santa2018['Close_KOSPI']

#주가 변동율 계산식: 주식 holding 시 다음날 기대수익률
santa2018['Daily_rtn_rate'] = santa2018['expected_rtns']/santa2018['Close_KOSPI']

santa2018['UPDOWN'] = [1 if santa2018['Daily_rtn_rate'].loc[date] > 0 else 0 for date in santa2018.index]

santa2018['Phase'] = ['상승' if x == 1 else '하락' for x in santa2018['UPDOWN']]
santa2018

C:\Users\LG\AppData\Local\Temp\ipykernel_12696\3919693071.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2018['Price_lag'] = santa2018['Close_KOSPI'].shift(-1)
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\3919693071.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2018['expected_rtns'] = santa2018['Price_lag']-santa2018['Close_KOSPI']
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\3919693071.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2018['Daily_rtn_rate'] = santa2018['expected_rtns']/santa2018['Close_KOSPI']
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\3919693071.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2018['UPDOWN'] = [1 if santa2018['Daily_rtn_rate'].loc[date] > 0 else 0 for date in santa2018.index]
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\3919693071.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2018['Phase'] = ['상승' if x == 1 else '하락' for x in santa2018['UPDOWN']]

코스피,Close_KOSPI,Price_lag,expected_rtns,Daily_rtn_rate,UPDOWN,Phase
날짜,,,,,,
2018-01-02,2479.65,2486.35,6.70,0.002702,1,상승
2018-01-03,2486.35,2466.46,-19.89,-0.008000,0,하락
2018-01-04,2466.46,2497.52,31.06,0.012593,1,상승
2018-01-05,2497.52,2513.28,15.76,0.006310,1,상승
2018-01-08,2513.28,2510.23,-3.05,-0.001214,0,하락
...,...,...,...,...,...,...
2018-12-21,2061.49,2055.01,-6.48,-0.003143,0,하락
2018-12-24,2055.01,2028.01,-27.00,-0.013139,0,하락
2018-12-26,2028.01,2028.44,0.43,0.000212,1,상승
2018-12-27,2028.44,2041.04,12.60,0.006212,1,상승
2018-12-28,2041.04,NaN,NaN,NaN,0,하락

In [51]:
santa2018['Phase'].value_counts()

Phase
상승    122
하락    122
Name: count, dtype: int64

## 산타 2019
- 상승 139 하강 109
- 주가 상승 국면

In [53]:
santa2019= df_kospi.loc["2019-01-02":"2019-12-30"]
santa2019

코스피         Close_KOSPI
날짜
2019-01-02      2010.00
2019-01-03      1993.70
2019-01-04      2010.25
2019-01-07      2037.10
2019-01-08      2025.27
...                 ...
2019-12-23      2203.71
2019-12-24      2190.08
2019-12-26      2197.93
2019-12-27      2204.21
2019-12-30      2197.67

[246 rows x 1 columns]

In [54]:
#다음날 종가 계산식
santa2019['Price_lag'] = santa2019['Close_KOSPI'].shift(-1)

#주식 홀딩하는 경우 다음 날의 기대 수익
santa2019['expected_rtns'] = santa2019['Price_lag']-santa2019['Close_KOSPI']

#주가 변동율 계산식: 주식 holding 시 다음날 기대수익률
santa2019['Daily_rtn_rate'] = santa2019['expected_rtns']/santa2019['Close_KOSPI']

santa2019['UPDOWN'] = [1 if santa2019['Daily_rtn_rate'].loc[date] > 0 else 0 for date in santa2019.index]

santa2019['Phase'] = ['상승' if x == 1 else '하락' for x in santa2019['UPDOWN']]
santa2019

C:\Users\LG\AppData\Local\Temp\ipykernel_12696\1503176765.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2019['Price_lag'] = santa2019['Close_KOSPI'].shift(-1)
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\1503176765.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2019['expected_rtns'] = santa2019['Price_lag']-santa2019['Close_KOSPI']
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\1503176765.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2019['Daily_rtn_rate'] = santa2019['expected_rtns']/santa2019['Close_KOSPI']
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\1503176765.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2019['UPDOWN'] = [1 if santa2019['Daily_rtn_rate'].loc[date] > 0 else 0 for date in santa2019.index]
C:\Users\LG\AppData\Local\Temp\ipykernel_12696\1503176765.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  santa2019['Phase'] = ['상승' if x == 1 else '하락' for x in santa2019['UPDOWN']]

코스피,Close_KOSPI,Price_lag,expected_rtns,Daily_rtn_rate,UPDOWN,Phase
날짜,,,,,,
2019-01-02,2010.00,1993.70,-16.30,-0.008109,0,하락
2019-01-03,1993.70,2010.25,16.55,0.008301,1,상승
2019-01-04,2010.25,2037.10,26.85,0.013357,1,상승
2019-01-07,2037.10,2025.27,-11.83,-0.005807,0,하락
2019-01-08,2025.27,2064.71,39.44,0.019474,1,상승
...,...,...,...,...,...,...
2019-12-23,2203.71,2190.08,-13.63,-0.006185,0,하락
2019-12-24,2190.08,2197.93,7.85,0.003584,1,상승
2019-12-26,2197.93,2204.21,6.28,0.002857,1,상승
2019-12-27,2204.21,2197.67,-6.54,-0.002967,0,하락
2019-12-30,2197.67,NaN,NaN,NaN,0,하락

In [55]:
santa2019['Phase'].value_counts()

Phase
상승    139
하락    107
Name: count, dtype: int64